# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'В очереди'), (1, 'Выполняется'), (2, 'Выполнено')]),
        ),
    ]
